baseURL = "https://ibrahim-rudn.github.io/"
title = "Ibrahim Hisseine Gana"
theme = "hugo-theme-terminal"

[params]
  contentTypeName = "posts"
  author = "Ibrahim Hisseine Gana"
  description = "Сайт научного работника"
